### ISSUE TITLE
Visual contribution 

### ISSUE THREAD

**Issue by cormullion** [simonbyrne/Pi.jl#1]
Hi Simon. I didn't want to sully your notebook with non-mathy stuff, but I thought you might like a picture of the first 5000 digits:

![pi](https://cloud.githubusercontent.com/assets/52289/23768131/e5ef8474-0502-11e7-9a92-13377d8d95a2.png)

The Julia source is [here](https://gist.github.com/cormullion/e979d819e478da73280faaeb67490888).

**Comment by simonbyrne** [comment]
Thanks, that's great! What's the method you're using to compute the digits? Care to do a short write up? (You can also plug Luxor.jl)

**Comment by cormullion** [comment]
I was hoping you could explain it; i haven't a clue how it works (can't remember where I got it from.)

**Comment by simonbyrne** [comment]
I've added the image as the header to the post. Maybe next year we can put together a writeup on how the digits came about.

**Comment by cormullion** [comment]
Cool, thanks for the shout. So, I've got a year to work out how it works... :)

**Comment by simonbyrne** [comment]
From what I can tell, it's based on one of the generalized continued fractions here: https://en.wikipedia.org/wiki/Pi#Continued_fractions
